### ISSUE TITLE
[Python] Fix heatmap in Mandelbrot

### ISSUE THREAD

**Issue by timueh** [timueh/Exercism#1]
I seem to misunderstand pyplot's `imshow()` function when [plotting the mandelbrot set from this file](https://github.com/timueh/CodeCompendium/tree/master/python/mandelbrot-set). I'd like to use something like

```python
plt.imshow(xAxis, yAxis, z)
```

which is working just fine for the [Julia version of the same code](https://github.com/timueh/CodeCompendium/blob/7c316c748b9a453868c6bff787b6c58ea766814e/julia/mandelbrot-set/mandelbrot_set.jl#L48).

**Comment by timueh** [comment]
Hey @friedue, perhaps you can help?

**Comment by timueh** [comment]
Hey @nicoleludwig, you might be able to help too? 😄

**Comment by friedue** [comment]
do you have an error message?

**Comment by timueh** [comment]
It's fine syntactically but incorrect semantically. What I want to see on the x- and y-axes is [like this (Julia version).](https://github.com/timueh/CodeCompendium/blob/MandelbrotHeatmaps/julia/mandelbrot-set/mandelbrot_julia.png) What I get instead is [like this (Python version):](https://github.com/timueh/CodeCompendium/blob/MandelbrotHeatmaps/python/mandelbrot-set/mandelbrot_python.png) wrong axes and off by 90 degrees.

Thanks!

**Comment by nicoleludwig** [comment]
for me changing the last lines to:
```python
z = np.reshape(z, (len(xAxis), len(yAxis)))
z = np.transpose(z)
plt.imshow(z, origin='lower')
plt.show()

ax = sns.heatmap(z)
plt.show(ax)
```
works to rotate the plot. I also like seaborn plots a bit more, hence the last plot in seaborn.

**Comment by timueh** [comment]
Nice! But what about getting the `xAxis` and `yAxis` plotted too? Like in the Julia version? I’d like something like `plt.imshow(xAxis, yAxis, z)`. Similar to the Julia version.

**Comment by nicoleludwig** [comment]
```python
plt.imshow(z, origin='lower', extent=[-2 ,0.3, -1, 1])
```

does the trick for me.
Unfortunately, I'm too stupid to do that in seaborn at the moment.

**Comment by timueh** [comment]
uhhh.. nice hack. but there’s got to be something cleaner, right?

**Comment by friedue** [comment]
based on [the documentation](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.imshow.html) I would try to transpose `Z`

and based on [these functions here](https://matplotlib.org/3.1.1/gallery/images_contours_and_fields/affine_image.html#sphx-glr-gallery-images-contours-and-fields-affine-image-py) I don't think there's a much more elegant solution than the one proposed by @nicoleludwig

**Comment by timueh** [comment]
[here's an even more detailed answer in the docs.](https://matplotlib.org/3.1.1/tutorials/intermediate/imshow_extent.html)

Thanks!
